[general]
dbpath = /var/lib/isso/comments.db
host =
    https://ec-buddhist-sangha.github.io
    https://eauclairesangha.org
    http://localhost:1313
log-file = /var/log/isso.log

[server]
listen = http://0.0.0.0:8080
public-endpoint = https://comments.eauclairesangha.org

[moderation]
enabled = false
purge-after = 30d

[markup]
; Mistune loads default plugins (strikethrough, subscript, superscript)

[hash]
salt = e9ea5681b67ff6be25d550b920fc376f
algorithm = pbkdf2

[guard]
enabled = true
ratelimit = 2
direct-reply = 3
reply-to-self = false
require-email = false
